# Numpy

## Python Library Used to compute the arithmetic mean along the specified axis, mostly deals with arrays

In [1]:
!pip install numpy

In [5]:
import numpy as np

# Creating a 1 dimensional array

In [49]:
my_list = [1, 2, 3, 4, 5, 8,9, 10, 11, 12, 13, 14, 15]
my_array=np.array(my_list)

In [8]:
type(my_array)

numpy.ndarray

In [9]:
my_array.shape

(7,)

# Creating a 2 dimensional array

In [14]:
my_list1 = [2, 3, 4, 5, 1,]
my_list2 = [1, 3, 8, 5, 2,]
my_list3 = [6, 9, 4, 7, 8,]

two_d=np.array([my_list1, my_list2, my_list3])

In [15]:
two_d

array([[2, 3, 4, 5, 1],
       [1, 3, 8, 5, 2],
       [6, 9, 4, 7, 8]])

In [16]:
two_d.shape

(3, 5)

In [18]:
# Reshaping the array in any shape I want

two_d.reshape(5, 3)

array([[2, 3, 4],
       [5, 1, 1],
       [3, 8, 5],
       [2, 6, 9],
       [4, 7, 8]])

In [19]:
two_d.reshape(15, )

array([2, 3, 4, 5, 1, 1, 3, 8, 5, 2, 6, 9, 4, 7, 8])

In [21]:
two_d.reshape(1, 15)

array([[2, 3, 4, 5, 1, 1, 3, 8, 5, 2, 6, 9, 4, 7, 8]])

# INDEXING

In [22]:
# 11   12   13   14   15
# 0    1    2    3    4 -> from left to right
# -5   -4   -3   -2   -1 -> from right to left

In [28]:
#Single dimensional array
one_array =np.array([2, 4, 6, 8, 10])

In [29]:
one_array

array([ 2,  4,  6,  8, 10])

In [30]:
one_array[2]

np.int64(6)

In [31]:
#Two dimensional array
two_d

array([[2, 3, 4, 5, 1],
       [1, 3, 8, 5, 2],
       [6, 9, 4, 7, 8]])

In [32]:
two_d[:]

array([[2, 3, 4, 5, 1],
       [1, 3, 8, 5, 2],
       [6, 9, 4, 7, 8]])

In [33]:
two_d[0]

array([2, 3, 4, 5, 1])

In [34]:
two_d[:,]

array([[2, 3, 4, 5, 1],
       [1, 3, 8, 5, 2],
       [6, 9, 4, 7, 8]])

In [35]:
two_d[1:,]

array([[1, 3, 8, 5, 2],
       [6, 9, 4, 7, 8]])

In [36]:
two_d[1:,3:]

array([[5, 2],
       [7, 8]])

In [37]:
two_d[:1,3:]

array([[5, 1]])

In [38]:
two_d[:2,3:]

array([[5, 1],
       [5, 2]])

# Understanding in built functions

In [42]:
#Inbuilt function
in_built1 =np.arange(1, 25)

In [44]:
in_built1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [45]:
#Inbuilt function with gaps
in_built1 =np.arange(1, 25, 3)

In [46]:
in_built1

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [48]:
#linspace function with gaps -> important for deep learning
np.linspace(1, 20, 30)

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

In [55]:
# The copy function
copy_func=np.array([1,  2,  3,  4,  5,  8,  9, 10, 11, 12, 13, 14, 15])

In [69]:
copy_func

array([  1,   2,   3, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150])

In [70]:
copy_func[3:]=150

In [58]:
copy_func

array([  1,   2,   3, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150])

In [59]:
copy_func1=copy_func

In [60]:
copy_func1[3:]=300
print(copy_func1)

[  1   2   3 300 300 300 300 300 300 300 300 300 300]


In [61]:
copy_func

array([  1,   2,   3, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300])

In [71]:
copy_func1=copy_func.copy()

In [72]:
print(copy_func)
copy_func1[3:]=300
print(copy_func1)

[  1   2   3 150 150 150 150 150 150 150 150 150 150]
[  1   2   3 300 300 300 300 300 300 300 300 300 300]


## Useful explanatory data data analysis conditions

In [73]:
copy_func

array([  1,   2,   3, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150])

In [75]:
my_var =3
copy_func[copy_func<=my_var]

array([1, 2, 3])

In [77]:
np.ones(8,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [78]:
np.ones((2,6),dtype=float)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [52]:
my_array1=my_array

In [54]:
my_array[3:]=200
print(my_array1)

[  1   2   3 200 200 200 200 200 200 200 200 200 200]
